### ISSUE TITLE
[CategoryManage] 카테고리 관리 화면 구성

### ISSUE THREAD

**Issue by sus0985** [sus0985/TODO-Android#1]
## TODO
- [x] 홈화면에서 카테고리 바에서 카테고리 관리 탭으로 넘어가도록 연결
- [x] 기존 카테고리 목록 보여주기
- [x] 카테고리 추가 기능
- [x] 카테고리 삭제 기능
- [x] 카테고리 수정 기능
